### ISSUE TITLE
Change "testserver.se" to variable

### ISSUE THREAD

**Issue by flysen** [flysen/shibboleth#3]
@LordBonkerz 
Instead of declare testserver.se
`shell: /etc/shibboleth/metagen.sh -2 -L -c /etc/shibboleth/sp-cert.pem -h testserver.se -e 'https://testserver.se/Shibboleth.sso' | grep -v 'POST-SimpleSign' > /etc/shibboleth/metadata.xml`

We should use: {{ applicationdefaults_entityid }} or {{ inventory_hostname }}
They reflect CNAME or SERVERname

https://github.com/flysen/shibboleth/blob/3a2f4642e42b624ff8ee7c4577f079d0edd2a499/tasks/main.yml#L42

**Comment by Moireabh** [comment]
indeed my Lord!

**Comment by flysen** [comment]
Changed to variables:
`shell: /etc/shibboleth/metagen.sh -A -2 -L -c /etc/shibboleth/sp-cert.pem -h {{ inventory_hostname }} -e '{{ applicationdefaults_entityid }}/Shibboleth.sso' | grep -v 'POST-SimpleSign' | grep -v 'PAOS' > /etc/shibboleth/metadata.xml`

```
<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://localhost/Shibboleth.sso/SLO/SOAP"/>
    <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://localhost/Shibboleth.sso/SLO/Redirect"/>
    <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://localhost/Shibboleth.sso/SLO/POST"/>
    <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="https://localhost/Shibboleth.sso/SLO/Artifact"/>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://localhost/Shibboleth.sso/SAML2/POST" index="1"/>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="https://localhost/Shibboleth.sso/SAML2/Artifact" index="3"/>
```

`<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" entityID="https://SERVER.uu.se/Shibboleth.sso">`
